{
 "title": "Tesla",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Charge Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT mean(\"battery_level\") FROM \"AllData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Range",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT last(\"battery_range\") FROM \"AllData\"",
     "select": [
      [
       { "params": [ "battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time To Charge",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT last(\"time_to_full_charge\") FROM \"AllData\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "time_to_full_charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Charge Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT last(\"battery_level\") FROM \"AllData\"",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Added This Session",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "Connected" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT LAST(EA) FROM (SELECT max(\"charge_energy_added\") AS EA FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Charging Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "kWhs",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ConnectedOdometer" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT kWhs FROM (SELECT max(\"charge_energy_added\") AS kWhs FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Drives - Energy Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "kWh Used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ConnectedOdometer" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT \"kWh Used\" FROM (SELECT  last(\"energy_used\") AS \"kWh Used\" FROM \"AllData\" WHERE (\"Connected\" = 'false') GROUP BY \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Wh / Mile",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "measurement": "AllData",
     "query": "SELECT SUM(EA) / (MAX(odometer) - MIN(odometer))*1000 AS WhPM FROM (SELECT max(\"charge_energy_added\") AS EA, max(\"odometer\") AS odometer FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Added",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "Connected" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT sum(EA) FROM (SELECT max(\"charge_energy_added\") AS EA FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Drives - kWh Per Mile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "kWh Per Mile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT kWh FROM (SELECT last(\"kwh_per_mile\") AS kWh FROM \"AllData\" WHERE (\"Connected\" = 'false') AND $timeFilter GROUP BY \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Miles Driven Per Day",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "lengthmi" }
   ],
   "targets": [
    {
     "alias": "Miles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AllData",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Miles Traveled",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "format": "lengthmi",
   "valueName": "current",
   "targets": [
    {
     "measurement": "AllData",
     "query": "SELECT last(\"odometer\") - first(\"odometer\") AS Traveled FROM \"AllData\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vampire Drain (6H+)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Vampire Drain",
     "groupBy": [
      { "params": [ "6h" ], "type": "time" }
     ],
     "measurement": "AllData",
     "select": [
      [
       { "params": [ "lostenergy_vampire" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Climate Control Drain (6H+)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Climate Drain",
     "groupBy": [
      { "params": [ "6h" ], "type": "time" }
     ],
     "measurement": "AllData",
     "select": [
      [
       { "params": [ "lostenergy_climate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}